version: '3'
services:
  frontend:
    tty: true
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile.frontend
    volumes:
      - ../../client:/client
  database:
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile.mysql
    volumes:
      - /srv/dev:/var/lib/mysql
    env_file:
      - ../sql.env
  express:
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile.express
    volumes:
      - ../../api:/api
    env_file:
      - ../../api/.env
  flask:
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile.flask
    volumes:
      - ../../pyapi:/pyapi
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - frontend
      - express
      - flask