CREATE TABLE Bingos (
  ID INT NOT NULL AUTO_INCREMENT,
  Name TEXT NOT NULL,
  FreeSpace TEXT,
  Description TEXT,
  PRIMARY KEY (ID)
);

CREATE TABLE Prompts (
  ID INT NOT NULL AUTO_INCREMENT,
  BingoID INT NOT NULL,
  PromptText TEXT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (BingoID) REFERENCES Bingos (ID)
);

CREATE TABLE Request (
  ID INT NOT NULL AUTO_INCREMENT,
  BingoID INT NOT NULL,
  PromptText TEXT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (BingoID) REFERENCES Bingos (ID)
);