FROM node:lts-alpine3.11

COPY ./client /client

WORKDIR /client

RUN npm install --only=prod --no-cache

RUN npm build --no-cache

FROM nginx:stable-alpine

COPY --from=0 ./build /var/www/html

COPY ./docker/prod/nginx.conf /etc/nginx/nginx.conf