FROM node:lts-alpine3.11 AS build-stage

COPY ./client /client

WORKDIR /client

RUN npm install --only=prod --no-cache

RUN npm run build

FROM nginx:stable-alpine AS deploy-stage

COPY --from=build-stage /client/build /var/www/html

COPY ./docker/prod/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

EXPOSE 443