FROM node:lts-alpine3.11 AS build-stage

WORKDIR /client

COPY ./client/* ./

RUN npm install --no-cache

COPY ./client ./

RUN npm run build

FROM nginx:stable-alpine AS deploy-stage

COPY --from=build-stage /client/build /var/www/

COPY ./docker/prod/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

EXPOSE 443